Hierarquia de centros de custo:
    RBG0000000: RBG
    SIGG000000: GG
    SIPG000000: PG
    SIRH000000: RH
    SISAO00000: SAO
    SIRCC00000: PGRC
    SIMAN00000: MAN
    SIOPE00000: OPE
    SISINFRA00: INFRA
    SINS000000: NS
    SIBS000000: BS
    SINSSP0000: SSP
    SINSAP0000: NSPRJ
    SISMS00000: SMS
    SINCOMPERJ: NSCOMPERJ
    SIECP00000: IE-CENPES
